name: CD

on:
  push:
    tags:
    - v*

jobs:
  Build-and-Tests:
    name: Build and Test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: running kafka
      run: |
        cd kafka
        docker-compose up -d
        sleep 2s        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Test
      run: |
        cd src
        dotnet clean 	        
        dotnet restore	      
        dotnet test
    - id: get_version
      uses: seungyongshim/get-version-action@v1.3
    - name: Modification Version
      run: |
        cd src
        sed -i "s/<Version>0.0.0.000/<Version>${{ steps.get_version.outputs.version }}/g" ./common.props
        cat ./common.props
    - name: Publish NuGet (SeungYongShim.Kafka.DependencyInjection)
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH:  src/SeungYongShim.Kafka.DependencyInjection/SeungYongShim.Kafka.DependencyInjection.csproj
        VERSION_FILE_PATH: src/common.props
        NUGET_KEY: ${{ secrets.api }}
        INCLUDE_SYMBOLS: true
        TAG_COMMIT: false